In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import sklearn as skl
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split

In [2]:
df=pd.DataFrame()
df=pd.read_csv('tmdb_5000_movies1.csv')

In [3]:
df.head()

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   
4        [{"name": "Walt Disney Pictures", "id": 2}]   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   12/10/2009  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...    5/19/2007   961000000   
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   10/26/2015   880674609   
3  [{"iso_3166_1": "US", "name": "United States o...    7/16/2012  1084939099   
4  [{"iso_3166_1": "US", "name": "United States o...     3/7/2012   284139100   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released   
4    132.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500  
2                                   Spectre           6.3        4466  
3                     The Dark Knight Rises           7.6        9106  
4                               John Carter           6.1        2124

In [4]:
for i in range(0,len(df.iloc[0])):
    if sum(df[df.columns[i]].isnull())>0:
        print('NaN values identified in ',df.columns[i],' and replaced by 0')
        df[df.columns[i]]=df[df.columns[i]].fillna(0)

NaN values identified in  homepage  and replaced by 0
NaN values identified in  overview  and replaced by 0
NaN values identified in  release_date  and replaced by 0
NaN values identified in  runtime  and replaced by 0
NaN values identified in  tagline  and replaced by 0


In [5]:
df_train, df_test = train_test_split(df, test_size=0.3)

In [6]:
df2=pd.DataFrame()
# df2['runtime'],df2['popularity']=df['runtime'],df['popularity']
# df2['budget'],df2['popularity'],df2['revenue']=df['budget'],df['popularity'],df['revenue']
df2['budget'],df2['popularity'],df2['revenue'],df2['runtime']=df['budget'],df['popularity'],df['revenue'],df['runtime']

In [7]:
# df2['production_companies']=df['production_companies']
# df2['production_countries']=df['production_countries']
# df2['genres']=df['genres']
# df2['original_language'],df2['status']=df['original_language'],df['status']
df2['original_language'],df2['status'],df2['genres']=df['original_language'],df['status'],df['genres']

In [8]:
import json
def get_data(column, dfA, key,opt):
    df_temp = pd.DataFrame([])
#     df2=pd.DataFrame([])
    for i in column:
        json_data = json.loads(i)
        df1 = pd.DataFrame.from_dict(json_data)
        if len(json_data) > opt:
            df2 = pd.DataFrame([df1[key][opt]])#opt > 0 require all json entries with more than one dicts inside
        else:
#             print(len(i),len(json_data),df1)
            df2 = df1
        df_temp = pd.concat([df_temp, df2], ignore_index=True)
#     dfB = pd.concat([dfB, df_temp], axis=1)
    return df_temp
X=get_data(df2['genres'],df2['genres'],"id",0)

In [9]:
X.rename(columns = {X.columns[0]:'genres'},inplace=True)
df2['genres']=X['genres']

In [10]:
arr_ol=pd.factorize(df2.original_language.unique())# 2 x n array for 1st as unique and 2nd as numbers
arr_s=pd.factorize(df2.status.unique())
for i in range(0,max(len(arr_ol[0]),len(arr_s[0]))):
    if i<len(arr_ol[0]):
        df2.original_language.replace(arr_ol[1][i],arr_ol[0][i],inplace=True)
    if i<len(arr_s[0]):
        df2.status.replace(arr_s[1][i],arr_s[0][i],inplace=True)
df2.genres=df2.genres.fillna(0)

In [11]:
df2.genres.unique()

array([   28.,    12.,    14.,    16.,   878.,    18.,    53., 10751.,
          35.,    36., 10752.,    37., 10749.,    80.,  9648.,    27.,
          99., 10402., 10770., 10769.,     0.])

In [12]:
from sklearn.linear_model import LinearRegression

In [13]:
x_train,x_test,y_train,y_test=train_test_split(df2,df['vote_average'],test_size=0.3)

In [14]:
Regression_model=LinearRegression()
Regression_model.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [15]:
Regression_model.score(x_train,y_train),Regression_model.score(x_test,y_test)

(0.22358818942555136, 0.1311437626065548)

In [18]:
for i, j in enumerate(x_train.columns):
    print("The coefficient for {} is {}".format(j, Regression_model.coef_[i]))
arr_coef=Regression_model.coef_
intercept=Regression_model.intercept_

The coefficient for budget is -5.428507120722712e-09
The coefficient for popularity is 0.007102742282451753
The coefficient for revenue is 8.932000528665034e-10
The coefficient for runtime is 0.01848850101584714
The coefficient for original_language is 0.02578643520564451
The coefficient for status is -1.2333839157314248
The coefficient for genres is -3.306375537275735e-07


In [35]:
df2.head()

budget  popularity     revenue  runtime  original_language  status  \
0  237000000  150.437577  2787965087    162.0                  0       0   
1  300000000  139.082615   961000000    169.0                  0       0   
2  245000000  107.376788   880674609    148.0                  0       0   
3  250000000  112.312950  1084939099    165.0                  0       0   
4  260000000   43.926995   284139100    132.0                  0       0   

   genres  
0    28.0  
1    12.0  
2    28.0  
3    28.0  
4    28.0

In [20]:
normdf=pd.DataFrame()
for i in df2.columns:
    X=pd.DataFrame((df2[i]-df2[i].min())/(df2[i].max()-df2[i].min()))
    normdf=pd.concat([normdf,X], axis=1)
normdf.head(2)

budget  popularity   revenue  runtime  original_language  status  \
0  0.623684    0.171815  1.000000  0.47929                0.0     0.0   
1  0.789474    0.158846  0.344696  0.50000                0.0     0.0   

     genres  
0  0.002600  
1  0.001114

In [21]:
0.8*0.2

0.16000000000000003

In [22]:
from sklearn.feature_selection import VarianceThreshold

In [23]:
sel = VarianceThreshold(threshold = 0.5)

In [24]:
Selector=sel.fit_transform(df2)
Selector[0:5]

array([[2.37000000e+08, 1.50437577e+02, 2.78796509e+09, 1.62000000e+02,
        0.00000000e+00, 2.80000000e+01],
       [3.00000000e+08, 1.39082615e+02, 9.61000000e+08, 1.69000000e+02,
        0.00000000e+00, 1.20000000e+01],
       [2.45000000e+08, 1.07376788e+02, 8.80674609e+08, 1.48000000e+02,
        0.00000000e+00, 2.80000000e+01],
       [2.50000000e+08, 1.12312950e+02, 1.08493910e+09, 1.65000000e+02,
        0.00000000e+00, 2.80000000e+01],
       [2.60000000e+08, 4.39269950e+01, 2.84139100e+08, 1.32000000e+02,
        0.00000000e+00, 2.80000000e+01]])

In [25]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression

In [26]:
X=df2
Y=df['vote_average']

In [27]:
lr=LinearRegression()

In [28]:
rfe = RFE(lr,n_features_to_select=1)
rfe.fit(X,Y)

RFE(estimator=LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False),
  n_features_to_select=1, step=1, verbose=0)

In [29]:
ranking=rfe.ranking_

In [30]:
ranking

array([6, 4, 7, 2, 3, 1, 5])

In [31]:
print ("Features sorted by their rank:")
print (sorted(zip(map(lambda x: round(x, 4), rfe.ranking_), df2)))

Features sorted by their rank:
[(1, 'status'), (2, 'runtime'), (3, 'original_language'), (4, 'popularity'), (5, 'genres'), (6, 'budget'), (7, 'revenue')]
